name: Staging Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - develop
env:
  FORCE_COLOR: true
  NODE_VERSION: lts/*
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Does something
        run: echo "Hello World"
  create_pr:
    name: Create New PR
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          destination_branch: staging
          pr_title: Promote develop to staging
          pr_body: Automated PR from develop to staging
          pr_reviewer: wopian
          pr_assignee: wopian
          pr_label: Priority%3A+3+-+Medium,Type%3A+Deployment
          pr_allow_empty: true
